# Generated by Django 5.2.16 on 2026-07-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='год')),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'Январь'), (2, 'Февраль'), (3, 'Март'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь'), (12, 'Декабрь')], verbose_name='месяц')),
                ('status', models.CharField(choices=[('open', 'Открыт'), ('closed', 'Закрыт')], default='open', max_length=20, verbose_name='статус')),
                ('is_archived', models.BooleanField(default=False, verbose_name='архив')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменен')),
            ],
            options={
                'verbose_name': 'расчетный период',
                'verbose_name_plural': 'расчетные периоды',
                'ordering': ('-year', '-month'),
                'constraints': [models.UniqueConstraint(fields=('year', 'month'), name='unique_accounting_period')],
            },
        ),
    ]
