# Generated by Django 5.2.16 on 2026-07-12 11:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personnel_number', models.CharField(blank=True, max_length=6, unique=True, verbose_name='табельный номер')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('normalized_full_name', models.CharField(db_index=True, editable=False, max_length=255, verbose_name='ФИО для поиска')),
                ('organization', models.CharField(blank=True, max_length=120, verbose_name='организация')),
                ('project', models.CharField(blank=True, max_length=255, verbose_name='проект')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='должность / категория')),
                ('employment_type', models.CharField(choices=[('staff', 'Штат'), ('contractor', 'Подрядчик'), ('other', 'Другое')], default='other', max_length=20, verbose_name='тип')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('archived', 'Архив')], default='active', max_length=20, verbose_name='статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменен')),
            ],
            options={
                'verbose_name': 'сотрудник',
                'verbose_name_plural': 'сотрудники',
                'ordering': ('full_name',),
            },
        ),
        migrations.CreateModel(
            name='EmployeeAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=255, verbose_name='ФИО из файла')),
                ('normalized_source_name', models.CharField(db_index=True, max_length=255, verbose_name='ФИО из файла для поиска')),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='источник')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='payroll.employee', verbose_name='сотрудник')),
            ],
            options={
                'verbose_name': 'алиас сотрудника',
                'verbose_name_plural': 'алиасы сотрудников',
                'constraints': [models.UniqueConstraint(fields=('normalized_source_name', 'source'), name='unique_employee_alias_per_source')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='ставка за час')),
                ('daily_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='ставка за день')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменена')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='payroll.employee', verbose_name='сотрудник')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_rates', to='core.accountingperiod', verbose_name='период')),
            ],
            options={
                'verbose_name': 'ставка сотрудника',
                'verbose_name_plural': 'ставки сотрудников',
                'ordering': ('period', 'employee__full_name'),
                'constraints': [models.UniqueConstraint(fields=('employee', 'period'), name='unique_employee_rate_period')],
            },
        ),
    ]
