# Generated by Django 5.2.16 on 2026-07-12 12:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimesheetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.PositiveSmallIntegerField(default=0, verbose_name='дни')),
                ('hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='часы')),
                ('daily_hours', models.JSONField(blank=True, default=dict, verbose_name='часы по дням')),
                ('source_name', models.CharField(blank=True, max_length=255, verbose_name='ФИО из табеля')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменен')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_entries', to='payroll.employee', verbose_name='сотрудник')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_entries', to='core.accountingperiod', verbose_name='период')),
            ],
            options={
                'verbose_name': 'строка табеля',
                'verbose_name_plural': 'табель',
                'ordering': ('period', 'employee__full_name'),
                'constraints': [models.UniqueConstraint(fields=('employee', 'period'), name='unique_timesheet_entry_period')],
            },
        ),
    ]
