# Generated by Django 5.2.16 on 2026-07-12 12:09

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('payroll', '0002_timesheetentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccrualRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premium', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='премия')),
                ('ktu', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='КТУ')),
                ('salary_1c', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='ЗП 1С')),
                ('daily_allowance_1c', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='суточные 1С')),
                ('previous_plus', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='плюс за пред. месяц')),
                ('previous_minus', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='минус за пред. месяц')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменен')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accrual_records', to='payroll.employee', verbose_name='сотрудник')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accrual_records', to='core.accountingperiod', verbose_name='период')),
            ],
            options={
                'verbose_name': 'начисление',
                'verbose_name_plural': 'начисления',
                'ordering': ('period', 'employee__full_name'),
                'constraints': [models.UniqueConstraint(fields=('employee', 'period'), name='unique_accrual_record_period')],
            },
        ),
    ]
