# Generated by Django 5.2.16 on 2026-07-12 12:14

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('payroll', '0003_accrualrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='сумма')),
                ('paid_at', models.DateField(verbose_name='дата выплаты')),
                ('initiator', models.CharField(max_length=255, verbose_name='инициатор')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменена')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payroll.employee', verbose_name='сотрудник')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.accountingperiod', verbose_name='период')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='автор изменения')),
            ],
            options={
                'verbose_name': 'выплата',
                'verbose_name_plural': 'выплаты',
                'ordering': ('-paid_at', 'employee__full_name'),
            },
        ),
    ]
