# Generated by Django 5.2.16 on 2026-07-12 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accrualrecord',
            name='previous_balance_manual_override',
            field=models.BooleanField(default=False, verbose_name='ручная корректировка переноса'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(max_length=100, verbose_name='объект')),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='ID объекта')),
                ('object_repr', models.CharField(blank=True, max_length=255, verbose_name='представление')),
                ('field_name', models.CharField(max_length=100, verbose_name='поле')),
                ('old_value', models.TextField(blank=True, verbose_name='старое значение')),
                ('new_value', models.TextField(blank=True, verbose_name='новое значение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата и время')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='автор')),
            ],
            options={
                'verbose_name': 'запись журнала',
                'verbose_name_plural': 'журнал изменений',
                'ordering': ('-created_at',),
            },
        ),
    ]
