# Generated by Django 5.2.16 on 2026-07-15 10:03

from django.db import migrations, models


def keep_latest_employee_rate(apps, schema_editor):
    EmployeeRate = apps.get_model('payroll', 'EmployeeRate')
    seen_employee_ids = set()
    duplicate_ids = []
    for rate in EmployeeRate.objects.order_by('employee_id', '-period_id', '-id'):
        if rate.employee_id in seen_employee_ids:
            duplicate_ids.append(rate.id)
        else:
            seen_employee_ids.add(rate.employee_id)
    if duplicate_ids:
        EmployeeRate.objects.filter(id__in=duplicate_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_accrualrecord_previous_balance_manual_override_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeerate',
            options={'ordering': ('employee__full_name',), 'verbose_name': 'ставка сотрудника', 'verbose_name_plural': 'ставки сотрудников'},
        ),
        migrations.RemoveConstraint(
            model_name='employeerate',
            name='unique_employee_rate_period',
        ),
        migrations.RunPython(keep_latest_employee_rate, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='employeerate',
            name='period',
        ),
        migrations.AddConstraint(
            model_name='employeerate',
            constraint=models.UniqueConstraint(fields=('employee',), name='unique_employee_rate'),
        ),
    ]
